name: Production

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-24.04

    steps:
    
    - name: "Checkout repository"
      uses: actions/checkout@v4
      
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v3
      
    - name: "Login to DockerHub"
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_ENDPOINT }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: "Build&Deploy"
      uses: docker/build-push-action@v5
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: |
          ${{ secrets.REGISTRY_ENDPOINT }}/${{ secrets.REGISTRY_ID }}/cicd:${{ github.sha }}
          ${{ secrets.REGISTRY_ENDPOINT }}/${{ secrets.REGISTRY_ID }}/cicd:latest
          ${{ secrets.REGISTRY_ENDPOINT }}/${{ secrets.REGISTRY_ID }}/cicd:${{ steps.extract_branch.outputs.branch }}


  deploy:

    runs-on: ubuntu-24.04
    needs: build

    steps:

    - name: "Run deploy on server"
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: 22
        script: |
          TEST_ENV = "${{ secrets.TEST_ENV }}" \
          docker compose -f /opt/cicd/docker-compose.yml up -d
